// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmaM_RC_DcJCHhC2QdO-jNv-hP4zXy-6g',
    appId: '1:816966958255:web:ce29d2a874ad619e8ca85a',
    messagingSenderId: '816966958255',
    projectId: 'flutterfirebaseapp-1be17',
    authDomain: 'flutterfirebaseapp-1be17.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-1be17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2cJUK1bckShaaqWckf8znrupLdwce4OI',
    appId: '1:816966958255:android:9bf05e826e561f038ca85a',
    messagingSenderId: '816966958255',
    projectId: 'flutterfirebaseapp-1be17',
    storageBucket: 'flutterfirebaseapp-1be17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxgnmJvMssPPU9HFbwhLFEAhye2zwbfFc',
    appId: '1:816966958255:ios:f16afb005820d4688ca85a',
    messagingSenderId: '816966958255',
    projectId: 'flutterfirebaseapp-1be17',
    storageBucket: 'flutterfirebaseapp-1be17.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxgnmJvMssPPU9HFbwhLFEAhye2zwbfFc',
    appId: '1:816966958255:ios:f16afb005820d4688ca85a',
    messagingSenderId: '816966958255',
    projectId: 'flutterfirebaseapp-1be17',
    storageBucket: 'flutterfirebaseapp-1be17.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmaM_RC_DcJCHhC2QdO-jNv-hP4zXy-6g',
    appId: '1:816966958255:web:c48aad36cda0db138ca85a',
    messagingSenderId: '816966958255',
    projectId: 'flutterfirebaseapp-1be17',
    authDomain: 'flutterfirebaseapp-1be17.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-1be17.firebasestorage.app',
  );
}
